[project]
name = "pyserialweb"
version = "0.0.5"
dependencies = []
classifiers = ["Programming Language :: Python :: 3", "Framework :: Pyodide"]

[build-system]
requires = ["setuptools", "pyodide-build"]
build-backend = "setuptools.build_meta"
